// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGxoFC9GYwgl8R26h01J55bXW2sbt3P_0',
    appId: '1:592166168144:web:ccfd6bb63e4e6b42711355',
    messagingSenderId: '592166168144',
    projectId: 'diabetes-70677',
    authDomain: 'diabetes-70677.firebaseapp.com',
    storageBucket: 'diabetes-70677.firebasestorage.app',
    measurementId: 'G-BZ42QLN2K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDieW5-_7L1SW_Bbr84f1qWPXoJGVnSKPg',
    appId: '1:592166168144:android:03d9275695e39bca711355',
    messagingSenderId: '592166168144',
    projectId: 'diabetes-70677',
    storageBucket: 'diabetes-70677.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGxoFC9GYwgl8R26h01J55bXW2sbt3P_0',
    appId: '1:592166168144:web:16f74fbf9db950c0711355',
    messagingSenderId: '592166168144',
    projectId: 'diabetes-70677',
    authDomain: 'diabetes-70677.firebaseapp.com',
    storageBucket: 'diabetes-70677.firebasestorage.app',
    measurementId: 'G-CVTQ2GNDHK',
  );
}
